name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile javascript and commit changes
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
          npm ci --no-audit --prefer-offline

      - name: Build
        run: npx webpack

      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'indigo_app/static/lib/external-imports.js indigo_app/static/javascript/indigo-app.js --force'
          message: 'Update compiled external-imports.js and indigo-app.js'
