name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile javascript and commit changes
    # avoid circular build commits
    if: ${{ !contains(github.event.head_commit.message, 'nobuild') }}
    steps:
      - uses: actions/checkout@v3
        with:
          # use a token that has admin perms to bypass direct commits to master
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      - name: Build javascript
        run: npx webpack

      - name: Copy node dependencies
        # Keep the local copy of some node dependencies up to date
        # indigo-web: only used for PDF exports
        run: |
          cp -R node_modules/indigo-web/scss indigo_app/static/lib/indigo-web/

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            - indigo_app/static/javascript/indigo/bluebell-monaco.js --force
            - indigo_app/static/javascript/indigo/editor.worker.*.js --force
            - indigo_app/static/lib/external-imports.js --force
            - indigo_app/static/javascript/indigo-app.js --force
            - indigo_app/static/lib/indigo-web/ --force
            - indigo/analysis/refs/provision_refs.py --force
          message: 'Update compiled bluebell-monaco.js, external-imports.js and indigo-app.js [nobuild]'
