name: Build l10n

on:
  push:
    branches:
      - l10n_master

concurrency:
  group: ${{ github.action }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile updated translations and commit changes
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          python -m pip install --upgrade pip
          pip install psycopg2==2.9.9
          pip install .

      - name: Compile messages
        run: python manage.py compilemessages

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          add: '*/locale/*/LC_MESSAGES/*.mo'
          message: 'Update compiled translations'
