name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile javascript and commit changes
    steps:
      - uses: actions/checkout@v2
        with:
          # use a token that has admin perms to bypass direct commits to master
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      - name: Build
        run: npx webpack

      - name: Import indigo-web
        # Keep the local copy of indigo-web up to date; this is only used for PDF exports
        run: cp -R node_modules/indigo-web/scss indigo_app/static/lib/indigo-web/

      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'indigo_app/static/lib/external-imports.js indigo_app/static/javascript/indigo-app.js indigo_app/static/lib/indigo-web/ --force'
          message: 'Update compiled external-imports.js and indigo-app.js'
